module.exports = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  CHANGE_NICKNAME: 'CHANGE_NICKNAME',
  RESTORE_MESSAGES: 'RESTORE_MESSAGES',
  ADD_SOCKET_CONNECTION: 'ADD_SOCKET_CONNECTION',
  UPDATE_CONNECTED_USERS: 'UPDATE_CONNECTED_USERS',
};
